# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/yenying/f91db070-879c-4386-9b31-69673baf0824/sportdata/Sport_project_v1.4.6/UI/3D_reconstruction/post_plt_setting.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 350)
        MainWindow.setMinimumSize(QtCore.QSize(612, 350))
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.sss = QtWidgets.QScrollArea(self.centralwidget)
        self.sss.setMaximumSize(QtCore.QSize(999, 16777215))
        self.sss.setWidgetResizable(True)
        self.sss.setObjectName("sss")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 230, 224))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.layoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 10, 207, 182))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_4.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_4.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_4.addWidget(self.radioButton_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_4.addWidget(self.radioButton_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_2.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_2.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_2.addWidget(self.lineEdit_4, 3, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.sss.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.sss)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.sss_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.sss_2.setWidgetResizable(True)
        self.sss_2.setObjectName("sss_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 346, 224))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 326, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_9.setEnabled(True)
        self.checkBox_9.setAutoFillBackground(False)
        self.checkBox_9.setCheckable(True)
        self.checkBox_9.setChecked(False)
        self.checkBox_9.setAutoRepeat(False)
        self.checkBox_9.setAutoExclusive(False)
        self.checkBox_9.setObjectName("checkBox_9")
        self.verticalLayout.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_10.setAutoFillBackground(False)
        self.checkBox_10.setCheckable(True)
        self.checkBox_10.setChecked(False)
        self.checkBox_10.setAutoRepeat(False)
        self.checkBox_10.setAutoExclusive(False)
        self.checkBox_10.setObjectName("checkBox_10")
        self.verticalLayout.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_11.setAutoFillBackground(False)
        self.checkBox_11.setCheckable(True)
        self.checkBox_11.setChecked(False)
        self.checkBox_11.setAutoRepeat(False)
        self.checkBox_11.setAutoExclusive(False)
        self.checkBox_11.setObjectName("checkBox_11")
        self.verticalLayout.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_12.setAutoFillBackground(False)
        self.checkBox_12.setCheckable(True)
        self.checkBox_12.setChecked(False)
        self.checkBox_12.setAutoRepeat(False)
        self.checkBox_12.setAutoExclusive(False)
        self.checkBox_12.setObjectName("checkBox_12")
        self.verticalLayout.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_13.setAutoFillBackground(False)
        self.checkBox_13.setCheckable(True)
        self.checkBox_13.setChecked(False)
        self.checkBox_13.setAutoRepeat(False)
        self.checkBox_13.setAutoExclusive(False)
        self.checkBox_13.setObjectName("checkBox_13")
        self.verticalLayout.addWidget(self.checkBox_13)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_14 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_14.setAutoFillBackground(False)
        self.checkBox_14.setCheckable(True)
        self.checkBox_14.setChecked(False)
        self.checkBox_14.setAutoRepeat(False)
        self.checkBox_14.setAutoExclusive(False)
        self.checkBox_14.setObjectName("checkBox_14")
        self.verticalLayout_2.addWidget(self.checkBox_14)
        self.checkBox_15 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_15.setAutoFillBackground(False)
        self.checkBox_15.setCheckable(True)
        self.checkBox_15.setChecked(False)
        self.checkBox_15.setAutoRepeat(False)
        self.checkBox_15.setAutoExclusive(False)
        self.checkBox_15.setObjectName("checkBox_15")
        self.verticalLayout_2.addWidget(self.checkBox_15)
        self.checkBox_16 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_16.setAutoFillBackground(False)
        self.checkBox_16.setCheckable(True)
        self.checkBox_16.setChecked(False)
        self.checkBox_16.setAutoRepeat(False)
        self.checkBox_16.setAutoExclusive(False)
        self.checkBox_16.setObjectName("checkBox_16")
        self.verticalLayout_2.addWidget(self.checkBox_16)
        self.checkBox_17 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_17.setAutoFillBackground(False)
        self.checkBox_17.setCheckable(True)
        self.checkBox_17.setChecked(False)
        self.checkBox_17.setAutoRepeat(False)
        self.checkBox_17.setAutoExclusive(False)
        self.checkBox_17.setObjectName("checkBox_17")
        self.verticalLayout_2.addWidget(self.checkBox_17)
        self.checkBox_18 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_18.setAutoFillBackground(False)
        self.checkBox_18.setCheckable(True)
        self.checkBox_18.setChecked(False)
        self.checkBox_18.setAutoRepeat(False)
        self.checkBox_18.setAutoExclusive(False)
        self.checkBox_18.setObjectName("checkBox_18")
        self.verticalLayout_2.addWidget(self.checkBox_18)
        self.checkBox_19 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_19.setAutoFillBackground(False)
        self.checkBox_19.setCheckable(True)
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setAutoRepeat(False)
        self.checkBox_19.setAutoExclusive(False)
        self.checkBox_19.setObjectName("checkBox_19")
        self.verticalLayout_2.addWidget(self.checkBox_19)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_20 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_20.setAutoFillBackground(False)
        self.checkBox_20.setCheckable(True)
        self.checkBox_20.setChecked(False)
        self.checkBox_20.setAutoRepeat(False)
        self.checkBox_20.setAutoExclusive(False)
        self.checkBox_20.setObjectName("checkBox_20")
        self.verticalLayout_3.addWidget(self.checkBox_20)
        self.checkBox_21 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_21.setAutoFillBackground(False)
        self.checkBox_21.setCheckable(True)
        self.checkBox_21.setChecked(False)
        self.checkBox_21.setAutoRepeat(False)
        self.checkBox_21.setAutoExclusive(False)
        self.checkBox_21.setObjectName("checkBox_21")
        self.verticalLayout_3.addWidget(self.checkBox_21)
        self.checkBox_22 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_22.setAutoFillBackground(False)
        self.checkBox_22.setCheckable(True)
        self.checkBox_22.setChecked(False)
        self.checkBox_22.setAutoRepeat(False)
        self.checkBox_22.setAutoExclusive(False)
        self.checkBox_22.setObjectName("checkBox_22")
        self.verticalLayout_3.addWidget(self.checkBox_22)
        self.checkBox_23 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_23.setAutoFillBackground(False)
        self.checkBox_23.setCheckable(True)
        self.checkBox_23.setChecked(False)
        self.checkBox_23.setAutoRepeat(False)
        self.checkBox_23.setAutoExclusive(False)
        self.checkBox_23.setObjectName("checkBox_23")
        self.verticalLayout_3.addWidget(self.checkBox_23)
        self.checkBox_24 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_24.setAutoFillBackground(False)
        self.checkBox_24.setCheckable(True)
        self.checkBox_24.setChecked(False)
        self.checkBox_24.setAutoRepeat(False)
        self.checkBox_24.setAutoExclusive(False)
        self.checkBox_24.setObjectName("checkBox_24")
        self.verticalLayout_3.addWidget(self.checkBox_24)
        self.checkBox_25 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_25.setAutoFillBackground(False)
        self.checkBox_25.setCheckable(True)
        self.checkBox_25.setChecked(False)
        self.checkBox_25.setAutoRepeat(False)
        self.checkBox_25.setAutoExclusive(False)
        self.checkBox_25.setObjectName("checkBox_25")
        self.verticalLayout_3.addWidget(self.checkBox_25)
        self.checkBox_26 = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_26.setAutoFillBackground(False)
        self.checkBox_26.setCheckable(True)
        self.checkBox_26.setChecked(False)
        self.checkBox_26.setAutoRepeat(False)
        self.checkBox_26.setAutoExclusive(False)
        self.checkBox_26.setObjectName("checkBox_26")
        self.verticalLayout_3.addWidget(self.checkBox_26)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.sss_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_6.addWidget(self.sss_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(37, 17, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMaximumSize(QtCore.QSize(90, 1677725))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 612, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Plot options"))
        self.radioButton.setText(_translate("MainWindow", "X axis"))
        self.radioButton_2.setText(_translate("MainWindow", "Y axis"))
        self.radioButton_3.setText(_translate("MainWindow", "Z axis"))
        self.radioButton_4.setText(_translate("MainWindow", "Velocity"))
        self.label_3.setText(_translate("MainWindow", "x range min:"))
        self.lineEdit.setText(_translate("MainWindow", "default"))
        self.label_4.setText(_translate("MainWindow", "x range max:"))
        self.lineEdit_2.setText(_translate("MainWindow", "default"))
        self.label_5.setText(_translate("MainWindow", "y range min:"))
        self.lineEdit_3.setText(_translate("MainWindow", "default"))
        self.label_6.setText(_translate("MainWindow", "y range max:"))
        self.lineEdit_4.setText(_translate("MainWindow", "default"))
        self.label.setText(_translate("MainWindow", "Point"))
        self.checkBox_9.setText(_translate("MainWindow", "nose"))
        self.checkBox_10.setText(_translate("MainWindow", "left eye"))
        self.checkBox_11.setText(_translate("MainWindow", "right eye"))
        self.checkBox_12.setText(_translate("MainWindow", "left ear"))
        self.checkBox_13.setText(_translate("MainWindow", "right ear"))
        self.checkBox_14.setText(_translate("MainWindow", "left shoulder"))
        self.checkBox_15.setText(_translate("MainWindow", "right shoulder"))
        self.checkBox_16.setText(_translate("MainWindow", "left elbow"))
        self.checkBox_17.setText(_translate("MainWindow", "right elbow"))
        self.checkBox_18.setText(_translate("MainWindow", "left wrist"))
        self.checkBox_19.setText(_translate("MainWindow", "right wrist"))
        self.checkBox_20.setText(_translate("MainWindow", "left hip"))
        self.checkBox_21.setText(_translate("MainWindow", "right hip"))
        self.checkBox_22.setText(_translate("MainWindow", "left knee"))
        self.checkBox_23.setText(_translate("MainWindow", "right knee"))
        self.checkBox_24.setText(_translate("MainWindow", "left ankle"))
        self.checkBox_25.setText(_translate("MainWindow", "right ankle"))
        self.checkBox_26.setText(_translate("MainWindow", "neck"))
        self.pushButton.setText(_translate("MainWindow", "Ok"))
